before_script:
  - apt-get update
  - apt-get install -y libibverbs-dev

build:
  only:
  - tags
  script:
  - "./autogen.sh"
  - "./contrib/configure-release --without-numa"
  - make
  - make dist
  - 'export upload_url=$(curl -s -H "Authorization: token $github_token" "https://api.github.com/repos/openucx/ucx/releases" | python -c "import sys,os,json; d=json.load(sys.stdin); rel = [r for r in d if r[\"tag_name\"] == os.environ[\"CI_COMMIT_TAG\"]]; print rel[0][\"upload_url\"]" | grep -oP "https\S+assets")'
  - 'export tar_name=$(ls *.tar.gz)'
  - 'curl -s -H "Authorization: token $github_token" -H "Content-Type: application/zip" --data-binary @"$tar_name" "${upload_url}?name=${tar_name}&label=${tar_name}"'

