# See https://aka.ms/yaml
# This pipeline to be run on tags creation

trigger:
  branches:
    include:
    - v*.*.x
# TMP - start upon push

  tags:
    include:
      - v*
pr:
  - master
  - v*.*.x

variables:
  DOCKER_OPT_VOLUMES: -v /hpc/local:/hpc/local

resources:
  containers:
    # x86_64
    - container: centos7_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/centos7-mofed5-cuda11:2
      options: $(DOCKER_OPT_VOLUMES)
    - container: centos8_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/centos8-mofed5-cuda11:2
    - container: ubuntu16_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu16.04-mofed5-cuda11:3
    - container: ubuntu18_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu18.04-mofed5-cuda11:3
    - container: ubuntu20_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu20.04-mofed5-cuda11:3
    - container: ubuntu22_cuda11_x86_64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu22.04-mofed5-cuda11:3
    # aarch64
    - container: centos8_cuda11_aarch64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/aarch64/centos8-mofed5-cuda11:2
    - container: ubuntu18_cuda11_aarch64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/aarch64/ubuntu18.04-mofed5-cuda11:3
    - container: ubuntu20_cuda11_aarch64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/aarch64/ubuntu20.04-mofed5-cuda11:3
    - container: ubuntu22_cuda11_aarch64
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/aarch64/ubuntu22.04-mofed5-cuda11:3

stages:
  - stage: Prepare
    jobs:
      - job: CheckRelease
        pool:
          name: MLNX
          demands:
          - ucx_docker -equals yes
        steps:
          - checkout: self
            fetchDepth: 100
            clean: true

          - bash: |
              set -eE
              source ./buildlib/az-helpers.sh
              set -x
              check_release_build $(Build.Reason) $(Build.SourceVersion) "AZP/RELEASE: "
            name: Result
            displayName: Check build condition

  - stage: GitHubDraft
    condition: eq(dependencies.Prepare.outputs['CheckRelease.Result.Launch'], 'True')
    dependsOn: Prepare
    jobs:
    - template: az-GitHubDraft.yml
      parameters:
        name: x86_64
        container: centos7_cuda11_x86_64
        demands: ucx_docker -equals yes

    - template: az-GitHubDraft.yml
      parameters:
        name: aarch64
        container: centos8_cuda11_aarch64
        demands: ucx_bf -equals yes


  - stage: Build
    displayName: Build binary packages
    dependsOn:
      - Prepare
      - GitHubDraft
    condition: eq(dependencies.Prepare.outputs['CheckRelease.Result.Launch'], 'True')
    jobs:
      - template: az-distro-release.yml
        parameters:
          name: x86_64
          demands: ucx_docker -equals yes

      - template: az-distro-release.yml
        parameters:
          name: aarch64
          demands: ucx_bf -equals yes


      - template: jucx/jucx-build.yml
        parameters:
          name: amd64   # x86_64
          container: centos7_cuda11_x86_64
          demands: ucx_docker -equals yes

      - template: jucx/jucx-build.yml
        parameters:
          name: aarch64
          container: centos8_cuda11_aarch64
          demands: ucx_bf -equals yes

      - template: jucx/jucx-publish.yml
        parameters:
          ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
            target: publish-release
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            target: package
